version: '3.1'

services:

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./:/var/www/html/
    working_dir: /var/www/html

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html/
    working_dir: /var/www/html

  db:
    image: mariadb:10.5.5
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: agrosty
      MYSQL_ROOT_PASSWORD: example

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025

